version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: product_catalog_db
    environment:
      POSTGRES_DB: catelog_tool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
